#!/usr/bin/env bash
# Post-deploy: Next.js standalone on PM2 with an auto-selected free port + Apache proxy.
set -euo pipefail

APP_DIR="${1:-/var/www/html/argusx.codemelodies.com}"
DEPLOY_ROOT="${2:-/var/www/html/argusx-deploy}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT_FILE="$APP_DIR/.runtime-port"
APACHE_PROXY="$DEPLOY_ROOT/apache/argusx-web-proxy.conf"
PM2_NAME="argusx-web"

# Shared VPS: avoid 3000-3015, 5000-5005, 6001, 8000-8080 — scan 3100-8999
WEB_PORT_START=3100
WEB_PORT_END=8999
if [ -f "$DEPLOY_ROOT/argusx-ports.conf" ]; then
  # shellcheck disable=SC1090
  source "$DEPLOY_ROOT/argusx-ports.conf"
  WEB_PORT_START="${ARGUSX_WEB_PORT_START:-3100}"
  WEB_PORT_END="${ARGUSX_WEB_PORT_END:-8999}"
fi

cd "$APP_DIR"

if ! command -v node >/dev/null 2>&1; then
  echo "Node.js is required on the VPS (recommended: Node 20 LTS)."
  exit 1
fi

if ! command -v pm2 >/dev/null 2>&1; then
  echo "PM2 is required. Install with: npm install -g pm2"
  exit 1
fi

PREFERRED=""
if [ -f "$PORT_FILE" ]; then
  PREFERRED="$(tr -d '[:space:]' < "$PORT_FILE")"
fi

PORT="$("$SCRIPT_DIR/find-free-port.sh" "$WEB_PORT_START" "$WEB_PORT_END" "$PREFERRED")"
echo "$PORT" > "$PORT_FILE"

cat > "$APP_DIR/ecosystem.config.cjs" <<EOF
module.exports = {
  apps: [
    {
      name: "${PM2_NAME}",
      cwd: "${APP_DIR}",
      script: "server.js",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      env: {
        NODE_ENV: "production",
        PORT: "${PORT}",
        HOSTNAME: "127.0.0.1",
      },
    },
  ],
};
EOF

mkdir -p "$(dirname "$APACHE_PROXY")"
cat > "$APACHE_PROXY" <<EOF
# Auto-generated by vps-post-deploy-web.sh — do not edit by hand.
ProxyPass / http://127.0.0.1:${PORT}/
ProxyPassReverse / http://127.0.0.1:${PORT}/
EOF

if pm2 describe "$PM2_NAME" >/dev/null 2>&1; then
  pm2 delete "$PM2_NAME" || true
fi

pm2 start "$APP_DIR/ecosystem.config.cjs"
pm2 save

echo "ArgusX web portal running on 127.0.0.1:${PORT} (PM2: ${PM2_NAME})"

if command -v sudo >/dev/null 2>&1 && sudo apache2ctl configtest >/dev/null 2>&1; then
  sudo apache2ctl configtest && sudo systemctl reload apache2
  echo "Apache reloaded with proxy port ${PORT}"
else
  echo "Apache reload skipped — ensure site includes: ${APACHE_PROXY}"
fi
